--Section1: Created Database "SQLQueryPractice".--
--Section2: Imported tables Customers,Orders and OrderDetails using flat file.--
--Section3: Wrote queries on join and case from 10 generated questions.--

/* 1. Write an SQL query to join the Customers, Orders, and Products tables 
and display Customer Name, Order ID, Product Name, Quantity, and Order Date.*/

SELECT
	C.FullName AS CustomerName,
	O.OrderID,
	OD.ProductName,
	OD.Quantity,
	O.OrderDate
FROM Orders O
LEFT JOIN Customers C
	ON C.CustomerID = O.CustomerID
JOIN OrderDetails OD
	ON O.OrderID = OD.OrderID;

/* 2. Write a query to list all customers and the total number of orders they
have placed using INNER JOIN and GROUP BY.*/

SELECT
	C.CustomerID,
	C.FullName AS CustomerName,
	COUNT(DISTINCT O.OrderID) AS TotalOrders
FROM Orders O
LEFT JOIN Customers C
	ON O.CustomerID = C.CustomerID 
JOIN OrderDetails OD
	ON O.OrderID = OD.OrderID
GROUP BY
	C.CustomerID,
	C.FullName;

/* 3. Write a query to calculate the total amount spent by each customer by
joining the three tables.*/

SELECT
	C.CustomerID,
	C.FullName AS CustomerName,
	SUM(OD.Total_Amount) AS TotalExpenditure
FROM Orders O
LEFT JOIN Customers C
	ON O.CustomerID = C.CustomerID
JOIN OrderDetails OD
	ON O.OrderID = OD.OrderID
GROUP BY
	C.CustomerID,
	C.FullName
ORDER BY CustomerID ASC;

/* 4. Write a query to identify the top 5 customers with the highest total 
purchases.*/

SELECT
	TOP 5 C.CustomerID,
	C.FullName AS CustomerName,
	C.Country,
	SUM(O.TotalAmount) AS TotalPurchase
FROM Orders O
LEFT JOIN Customers C
	ON O.CustomerID = C.CustomerID
GROUP BY
	C.CustomerID,
	C.FullName,
	C.Country
ORDER BY TotalPurchase DESC;

/* 5. Write a query to display each product and the number of different customers
who purchased it.*/

SELECT
	OD.ProductName,
	COUNT(DISTINCT C.CustomerID) AS CustomerPurchased	
FROM Orders O
JOIN Customers C
	ON O.CustomerID = C.CustomerID
JOIN OrderDetails OD
	ON O.OrderID = OD.OrderID
GROUP BY
	OD.ProductName
ORDER BY CustomerPurchased DESC;


/* 6. Write a query to find customers who have ordered more than one different 
product.*/

SELECT
	C.CustomerID,
	C.FullName AS CustomerName,
	COUNT(DISTINCT OD.ProductName) AS DifferentProductOrdered
FROM Customers C
JOIN Orders O
	ON C.CustomerID = O.CustomerID
JOIN OrderDetails OD
	ON O.OrderID = OD.OrderID
GROUP BY
	C.CustomerID,
	C.FullName
HAVING COUNT(DISTINCT OD.ProductName) > 1;

/* 7. Write a query to display the total revenue generated by each product category 
using the joined tables.*/

SELECT
	OD.ProductName,
	SUM(OD.Total_Amount) AS TotalRevenue
FROM Orders O
JOIN Customers C
	ON O.CustomerID = C.CustomerID
JOIN OrderDetails OD
	ON O.OrderID = OD.OrderID
GROUP BY
	OD.ProductName
ORDER BY TotalRevenue DESC;

/* 8. Write a query to find customers who have never purchased a specific product
(use an appropriate JOIN).*/

SELECT
	C.CustomerID,
	C.FullName AS CustomerName,
	C.Country
FROM Customers C
LEFT JOIN Orders O
	ON C.CustomerID = O.CustomerID 
LEFT JOIN OrderDetails OD
	ON O.OrderID = OD.OrderID
	AND OD.ProductName = 'Keyboard'
WHERE OD.ProductName IS NULL;

/* 9. CASE Question: Join the tables and use a CASE statement to classify customers as 
'High Value' when their total spending is greater than 1000, otherwise 'Regular Customer'.*/

SELECT
	C.CustomerID,
	C.FullName AS CustomerName,
	C.Email,
	C.Country,
	O.[Status],
	OD.ProductName,
	SUM(OD.Total_Amount) AS TotalExpenditure,
	CASE
		WHEN SUM(OD.Total_Amount) > 1000 THEN 'High Value'
		ELSE 'Regular Customer'
	END AS CustomerCategory 
FROM Orders O
LEFT JOIN Customers C
	ON O.CustomerID = C.CustomerID
JOIN OrderDetails OD
	ON O.OrderID = OD.OrderID
GROUP BY
	C.CustomerID,
	C.FullName,
	C.Email,
	C.Country,
	O.[Status],
	OD.ProductName
ORDER BY TotalExpenditure DESC;
	
/* 10.CASE Question: Join the tables and use a CASE statement to classify orders as 'Large 
Order' when Quantity >= 10, 'Medium Order' when Quantity is between 5 and 9, otherwise 
'Small Order'*/

SELECT
	C.CustomerID,
	C.FullName AS CustomerName,
	C.Email,
	C.Country,
	O.[Status],
	OD.ProductName,
	SUM(OD.Quantity) AS TotalQuantity,
	CASE
		WHEN SUM(OD.Quantity) >= 10 THEN 'Large Order'
		WHEN  SUM(OD.Quantity) BETWEEN 5 AND 9 THEN 'Medium Order'
		ELSE 'Small Order'
	END AS OrderCategory
FROM Orders O
LEFT JOIN Customers C
	ON O.CustomerID = C.CustomerID
JOIN OrderDetails OD
	ON O.OrderID = OD.OrderID
GROUP BY 
	C.CustomerID,
	C.FullName,
	C.Email,
	C.Country,
	O.[Status],
	OD.ProductName
ORDER BY TotalQuantity DESC;
